/**
 * Public identity for this deployment.
 *
 * Generated by scripts/configure-template.mjs. It contains no secrets.
 */
export const siteConfig = {
  name: "Phone Sticker Sponsorship",
  tagline: "Let your brand travel",
  siteUrl: "https://phone-sticker-sponsorship.example.com",
  owner: {
    name: "The maker",
    email: "hello@example.com",
    xUrl: "",
  },
} as const;
